import chromatix.functional as cx
import jax.numpy as jnp

# We first create an empty field.
field = cx.empty_field(
    shape=(512, 512), dx=1.0, spectrum=0.532, spectral_density=1.0, polarized=True
)

print(field.shape)
# And then turn it into the field generated by the point source afterb the lens.
k = jnp.array([0.0, 1.0])
E0 = jnp.ones((3,))

field = cx.vector_plane_wave(field, k, E0)
print(field.shape)
