name: Ruff
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync --extra dev
      - name: Lint with ruff
        run: uv run ruff format --check .
      - name: Format with ruff
        run: uv run ruff check --output-format=github --fix .