name: Ruff
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.16"
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: "pyproject.toml"
      - name: Install the project
        run: uv sync --extra dev
      - name: Lint with ruff
        run: uv run ruff format --check .
      - name: Format with ruff
        run: uv run ruff check --output-format=github --fix .
