name: Format and lint
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.4.8
      - name: Lint with ruff
        run: ruff format .
      - name: Format with ruff
        run: ruff --output-format=github --fix .